package com.cloudkitchens;

import com.cloudkitchens.model.Order;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import java.io.IOException;
import java.lang.reflect.Type;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private static final Logger log = LoggerFactory.getLogger(App.class);
    private static final Type ORDER_TYPE = new TypeToken<List<Order>>() {}.getType();

    public static void main(String[] args) throws IOException {
        String inputJsonFile = args[0];

        ApplicationContext ctxt = new AnnotationConfigApplicationContext(SpringConfig.class);

        OrderTaker orderTaker = ctxt.getBean(OrderTaker.class);
        orderTaker.start();

        Gson gson = new Gson();
        Path path = Paths.get(inputJsonFile);
        JsonReader reader = new JsonReader(Files.newBufferedReader(path));

        List<Order> orders = gson.fromJson(reader, ORDER_TYPE);

        OrderMaker orderMaker = ctxt.getBean(OrderMaker.class);
        try {
            orderMaker.startMakingOrder(orders.iterator());
        } catch (InterruptedException e) {
            log.error("Exception while making orders.", e);
        }
    }
}
